### ISSUE TITLE
does not work past page 1300

### ISSUE THREAD

**Issue by TobiasPrt** [notionplusid/core#1]
Hi,
I love the project. Since we use Notion for everything at our startup, including task management, we needed this!
Creating a workaround with the parent database is just unbearable.
Unfortunately, when using this plugin, it does stop adding numbers past 1300. About 63 pages need to be numbered for us.

We use the app in version 2.1.11, and I don't see any errors in the console, though I'm quite unfamiliar with how Notion extensions work. Is it a limitation of Google Cloud and we need to host it ourselves?

If you need anything else, please let me know.

Best

**Comment by kostkobv** [comment]
Hey @TobiasPrt 
Let me check please why this issue might be occurring. 
To confirm, you are using the publicly available extension?

**Comment by kostkobv** [comment]
I have also just pushed out an update that might address the issue you're having. 
Please let me know if that worked! 🙏

**Comment by TobiasPrt** [comment]
Yes, we're using the public extension.
Thank you for the quick response, your fix has resolved it and it works like a charm now, love your work!
